#!/usr/bin/env python
import sys
import os
import subprocess

pylib_dir = os.environ['_DEVOPS_ROOT'] + "/share/devops/"
sys.path.insert(0, pylib_dir)
import devop_config

CONFIG = devop_config.config()

def http_logs(role=None):
    log_files=('/var/log/apache2/access.log',
           '/var/log/apache2/error.log')

    for lf in log_files:
        devop_config.ssh_cmd('tail -n 50 {0}'.format(lf), role=role)


def system_logs(role=None):
    log_files=('/var/log/syslog',
           '/var/log/auth.log')

    for lf in log_files:
        devop_config.ssh_cmd('tail -n 50 {0}'.format(lf), role=role)


def main():
    (options, args) = devop_config.devop_args().parse_args()

    if len(sys.argv) < 1:
        print("Not enough arguments")
        sys.exit(1)

    switcher = {
        'http': http_logs,
        'system' : system_logs,

    }

    if sys.argv[1] not in switcher.keys():
        print("command not valid")
        sys.exit(1)

    func = switcher.get(sys.argv[1].strip(), lambda: "nothing")

    func(role=options.role)

if __name__ == "__main__":
	main()
