#!/usr/bin/env python
import sys
import os
import subprocess

pylib_dir = os.environ['_DEVOPS_ROOT'] + "/share/devops/"
sys.path.insert(0, pylib_dir)
import devop_config

CONFIG = devop_config.config()

def show_disk(role=None):
    disk_cmds=('df -h',
           'lsblk -io KNAME,TYPE,SIZE,MODEL',)

    for dc in disk_cmds:
        devop_config.ssh_cmd('{}'.format(dc), role=role)

def main():
    parser = devop_config.devop_args()
    args = parser.parse_args()

    if args.role is not None:
        role=args.role
    else:
        role=CONFIG.get('defaults','role')

    show_disk(role)

if __name__ == "__main__":
	main()
