#!/usr/bin/env python
import sys
import os
import subprocess

pylib_dir = os.environ['_DEVOPS_ROOT'] + "/share/devops/"
sys.path.insert(0, pylib_dir)
import devop_config

CONFIG = devop_config.config()

def apache_start(role=None):
    devop_config.ssh_cmd('sudo service apache2 start',role=role)

def apache_stop(role=None):
    devop_config.ssh_cmd('sudo service apache2 stop', role=role)

def apache_restart(role=None):
    devop_config.ssh_cmd('sudo service apache2 restart', role=role)

def apache_reload(role=None):
    devop_config.ssh_cmd('sudo service apache2 reload', role=role)

def apache_status(role=None):
    devop_config.ssh_cmd('/etc/init.d/apache2 status', role=role)


def test(role=None):
    devop_config.ssh_cmd('curl http://localhost:80', role=role)

def main():
    switcher = {
        'start': apache_start,
        'stop' : apache_stop,
        'restart': apache_restart,
        'reload':apache_reload,
        'status': apache_status,
        'test' : test,

    }

    parser = devop_config.devop_args()
    parser.add_argument('command', choices=switcher.keys())
    args = parser.parse_args()

    if args.role is not None:
        role=args.role
    else:
        role=CONFIG.get('defaults','role')

    func = switcher.get(args.command, lambda: "nothing")
    func(role=role)

if __name__ == "__main__":
	main()
