#!/usr/bin/env python
# Usage: devops key [-h] {new,list,upload,replace}
# Summary: Manage nova SSH Keys

import sys
import os
import subprocess

pylib_dir = os.environ['_DEVOPS_ROOT'] + "/share/devops/"
sys.path.insert(0, pylib_dir)
import devop_config
import argparse
from os.path import expanduser

HOME = expanduser("~")
CONFIG = devop_config.config()

def key_new():
    devop_config.ssh_cmd('ssh-keygen -N "" -f {}/.ssh/id_rsa'.format(HOME), host='local')

def key_upload():
    devop_config.ssh_cmd('nova keypair-add --pub-key {}/.ssh/id_rsa.pub workshop'.format(HOME), host='local')

def key_list():
    devop_config.ssh_cmd('nova keypair-list', host='local')

def key_replace():
    devop_config.ssh_cmd('nova keypair-delete workshop'.format(HOME), host='local')
    key_upload()

def main():
    switcher = {
        'new': key_new,
        'upload' : key_upload,
        'list': key_list,
        'replace': key_replace
    }

    parser = argparse.ArgumentParser()
    parser.add_argument('command', choices=switcher.keys())
    args = parser.parse_args()

    func = switcher.get(args.command, lambda: "nothing")
    func()

if __name__ == "__main__":
	main()
