#!/usr/bin/env python
import sys
import os
import subprocess

pylib_dir = os.environ['_DEVOPS_ROOT'] + "/share/devops/"
sys.path.insert(0, pylib_dir)
import devop_config

CONFIG = devop_config.config()

def apache_start(role=None):
    devop_config.ssh_cmd('sudo service apache2 start',role=role)

def apache_stop(role=None):
    devop_config.ssh_cmd('sudo service apache2 stop', role=role)

def apache_restart(role=None):
    devop_config.ssh_cmd('sudo service apache2 restart', role=role)

def apache_reload(role=None):
    devop_config.ssh_cmd('sudo service apache2 reload', role=role)

def apache_status(role=None):
    devop_config.ssh_cmd('/etc/init.d/apache2 status', role=role)


def test(role=None):
    devop_config.ssh_cmd('curl http://localhost:80', role=role)

def main():
    (options, args) = devop_config.devop_args().parse_args()


    if len(sys.argv) == 2:
        pass
    elif len(sys.argv) < 2:
        print("Not enough arguments")
        sys.exit(1)

    switcher = {
        'start': apache_start,
        'stop' : apache_stop,
        'restart': apache_restart,
        'reload':apache_reload,
        'status': apache_status,
        'test' : test,

    }

    if sys.argv[1] not in switcher.keys():
        print("command not valid")
        sys.exit(1)

    func = switcher.get(sys.argv[1].strip(), lambda: "nothing")

    func(role=options.role)

if __name__ == "__main__":
	main()
